# version: '2'

services:
  server:
    build: backend/.
    command: python app.py
    env_file:
      - '.env'
    volumes:
      - './backend:/backend'
    ports:
      - '8000:8000'

  frontend:
    build: './frontend'
    command: npm run start
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - './frontend/:/frontend'
      - '/frontend/node_modules'
